// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, port;

  express = require("express");

  port = 3000;

  app = express();

  app.engine(".html", require("ejs").__express);

  app.set("views", __dirname + "/views");

  app.set("view engine", "html");

  app.use("/static", express["static"](__dirname + "/public"));

  app.get("/", function(req, res) {
    return res.render("index", {});
  });

  app.listen(port);

  console.log("Listening on port " + port);

}).call(this);
