// Generated by CoffeeScript 1.3.3
(function() {
  var Connection, Db, Server, dbName, withCollection;

  Db = require("mongodb").Db;

  Connection = require("mongodb").Connection;

  Server = require("mongodb").Server;

  dbName = "fleague";

  withCollection = function(colName, fn) {
    return Db.connect("mongodb://localhost/" + dbName, function(err, db) {
      return db.collection(colName, function(err, collection) {
        return fn(collection);
      });
    });
  };

  exports.createLeague = function(league, callback) {
    return withCollection("leagues", function(coll) {
      var uniqueCode;
      console.log("CREATE LEAGUE " + league.name);
      uniqueCode = "XY1234";
      return callback(uniqueCode);
    });
  };

}).call(this);
