// Generated by CoffeeScript 1.3.3
(function() {
  var crypto, iterations, len;

  crypto = require("crypto");

  len = 128;

  iterations = 12000;

  exports.hash = function(pwd, salt, fn) {
    if (arguments.length === 3) {
      return crypto.pbkdf2(pwd, salt, iterations, len, fn);
    } else {
      fn = salt;
      return crypto.randomBytes(len, function(err, salt) {
        if (err) {
          return fn(err);
        }
        salt = salt.toString("base64");
        return crypto.pbkdf2(pwd, salt, iterations, len, function(err, hash) {
          if (err) {
            return fn(err);
          }
          return fn(null, salt, hash);
        });
      });
    }
  };

}).call(this);
